### ISSUE TITLE
hello! when will the toolkit be released? 

### ISSUE THREAD

**Issue by nathanawmk** [IBM/fhe-toolkit-linux#1]
hello! when will this toolkit be released?  

Nathan Aw (Singapore)

**Comment by faberga** [comment]
hi @nathanawmk and @sayoojsamuel   Tentativelly we are shooting for 1st half of Juy.
Keep an eye on our Announcements channel on slack https://join.slack.com/t/fhekit/shared_invite/zt-e35rax8l-_ZbB2XuF3WcXCM2mDe~AZQ

**Comment by dowem** [comment]
Hi  @nathanawmk Thanks for your patience and continued interest in our toolkit and FHE. Please check out the new code drop in GitHub. On behalf of the toolkit team, we hope you have fun!
