### ISSUE TITLE
Persistent Data Mode isn't working as expected on zCX

### ISSUE THREAD

**Issue by rosielickorish** [IBM/fhe-toolkit-linux#11]
**Describe the bug**
Persistent mode isn't working as expected on zCX or WLS, instead the toolkit displays a message that its couldn't create CMakeLists.txt file and keeps on searching for it.

**To Reproduce**
1. After fetching the pre-built container,  run the ./RunToolkit.sh -p ubuntu
2. At the VSCode editor you will see the error.

**Expected behavior**
The docs should be updated to point out the workaround which is too run in sandbox mode with the `-s` flag -> `./RunToolkit.sh -p -s ubuntu`.

**Environment (please complete the following information):**
 - Host Info (The machine hosting the FHE Toolkit Docker container), please provide the output of running the following commands in a termina window:
   - `uname -` 
`Linux lnxsec1 4.18.0-193.6.3.el8_2.s390x #1 SMP Mon Jun 1 20:38:45 UTC 2020 s390x s390x s390x GNU/Linux`
   - `ulimit -a`
```
core file size (blocks, -c) unlimited
data seg size (kbytes, -d) unlimited
scheduling priority (-e) 0
file size (blocks, -f) unlimited
pending signals (-i) 15275
max locked memory (kbytes, -l) 64
max memory size (kbytes, -m) unlimited
open files (-n) 1024
pipe size (512 bytes, -p) 8
POSIX message queues (bytes, -q) 819200
real-time priority (-r) 0
stack size (kbytes, -s) 8192
cpu time (seconds, -t) unlimited
max user processes (-u) 15275
virtual memory (kbytes, -v) unlim
```
 - Docker version (run `docker -v` in Terminal): `podman version 1.6.4`
 - Toolkit platform (Fedora, CentOS, Ubuntu): `ubuntu`

**Comment by rosielickorish** [comment]
This issue is also occuring on WSL.

**Comment by dowem** [comment]
I suspect this issue is the same or related to https://github.com/IBM/fhe-toolkit-linux/issues/28

**Comment by boland25** [comment]
@deanthomasson this is most likely fixed with the last merge but we need to test

**Comment by dowem** [comment]
@boland25 can we find some time to test this one tomorrow morning before you get into your usual work for the day? If it was sorted with that merge we can close this one out 🤞🏻

**Comment by boland25** [comment]
@deanthomasson confirmed that it is working as expected ok to close
