### ISSUE TITLE
ML-HElib training a model from scratch

### ISSUE THREAD

**Issue by WeberJulian** [IBM/fhe-toolkit-linux#116]
I've been through the documentation of the ML-HElib library and I haven't seen anything that allows for training a model.
Is training a model from scratch possible with the fhe-toolkit you released ? Or is this just for inference and you have a library in-house to train the models ?

Thanks

**Comment by dubek** [comment]
@WeberJulian thanks for your interest in FHE Toolkit.

Training a model from scratch isn't currently available through the FHE Toolkit.

**Comment by WeberJulian** [comment]
Ok thanks for the info
