### ISSUE TITLE
Change bats library to bats-core

### ISSUE THREAD

**Issue by boland25** [IBM/fhe-toolkit-linux#132]
**Describe the bug**
Currently our ubuntu, fedora, and alpine libraries rely on bats in the package managers to install bats.  However, we should be using bats-core
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Host Info (The machine hosting the FHE Toolkit Docker container), please provide the output of running the following commands in a termina window:
   - `uname -`
   - `ulimit -a`
 - Docker version (run `docker -v` in Terminal):
 - Toolkit platform (Fedora, CentOS, Ubuntu):

**Additional context**

**Comment by dowem** [comment]
I think the patch addresses one of the distros but did it address all of them?

**Comment by boland25** [comment]
Centos and alpine already had it setup this way. I originally relied on the package repos for Ubuntu and Fedora and they turned out to be the wrong package

**Comment by dowem** [comment]
OK then merged and closed!  Thanks for slaying another issue @deanthomasson !
