### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by hebabaze** [IBM/fhe-toolkit-linux#151]
Even though I proceeded with the advanced installation. I found the same error when I click on "launch selected target"

I am using ubuntu in vmware machine

**To Reproduce**
1. Go to '127.0.0.1:8443'
2. choose  the kits from the dropdown.
2. Click on Build
3. click on launch the selected target'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/54450458/116157861-ff8fb480-a6ed-11eb-9971-b609530bb2f6.png)

![image](https://user-images.githubusercontent.com/54450458/116157944-1e8e4680-a6ee-11eb-85a7-9954bf9af122.png)

**Environment (please complete the following information):**
 - Host Info (The machine hosting the FHE Toolkit Docker container), please provide the output of running the following commands in a termina window:
 - `uname -a : Linux myhost 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 - `ulimit -a`
 
![image](https://user-images.githubusercontent.com/54450458/116158485-108cf580-a6ef-11eb-89af-8f7f0b28c144.png)

 - Docker version (run `docker -v` in Terminal): Docker version 20.10.2, build 20.10.2-0ubuntu1~18.04.2
 - Toolkit platform (Fedora, CentOS, Ubuntu): Ubuntu

**Additional context**

**Comment by hebabaze** [comment]
I think it's ok 
![image](https://user-images.githubusercontent.com/54450458/116163938-0e2f9900-a6f9-11eb-83ca-f9dd330a762c.png)
I changed the number of core and CPU in VMware setting i choose only

**Comment by boland25** [comment]
@hebabaze are you confirming that you have it working?

**Comment by hebabaze** [comment]
@boland25 

- First to successful the build i had to change  two lines in BuildDockerImage.sh ,line 115 to update the boost download link and and line 322 to avoid the 0 id

- for the two examples **BGV_world_country_db_lookup** and **CKKS_credit_card_fraud** the build and execution it was by default successful 

- This is print screen for  a extract of the output of  **CKKS_credit_card_fraud**
print 1
![image](https://user-images.githubusercontent.com/54450458/116281905-77132180-a78a-11eb-9a48-04055b1b4559.png)
print 2
![image](https://user-images.githubusercontent.com/54450458/116282122-af1a6480-a78a-11eb-9a0a-d124422764fe.png)


- For the other examples i get this warning when i tape ` cmake .`

![image](https://user-images.githubusercontent.com/54450458/116272059-de2bd880-a780-11eb-921f-9b5958678c42.png)

and when i tapke `make` iget this error 
![image](https://user-images.githubusercontent.com/54450458/116271819-a15fe180-a780-11eb-9a8e-fe20603372b8.png)

After that i see that the CmakeList.txt is different to other file so i add those lines with respecting project  name :
```
cmake_minimum_required(VERSION 3.10)
project(BGV_binary_arithmetic VERSION 0.0.1 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_CXX_FLAGS "-Werror -fopenmp -Wfatal-errors")
## Rely on the Environment variable to dictate which version of helib to use
set(HELIB_VERSION ${HELIB_CMAKE_LISTS_VERSON})
find_package(helib ${HELIB_VERSION} REQUIRED)
find_package(Boost 1.72.0 EXACT REQUIRED COMPONENTS filesystem system thread)
find_package(HDF5 REQUIRED COMPONENTS CXX)
include_directories(${HDF5_INCLUDE_DIR})

```
after i could launch the executable **/BGV_binary_arithmetic** and i get this output 
![image](https://user-images.githubusercontent.com/54450458/116281212-c442c380-a789-11eb-9e08-0ad163097994.png)
![image](https://user-images.githubusercontent.com/54450458/116281291-da508400-a789-11eb-8ff0-b63abff5ba57.png)
