### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Hang-shao** [IBM/fhe-toolkit-linux#162]
# Where
For the next step, one should be aware of a mathematical result known as
Fermat's little theorem (FLT). FLT states that given any non-zero integer a
and a prime number p then a raised to the power p-1 always results in a
number pn + 1 where n is an integer.

# What 
This is a problem. What is n?
FLT：a^p-1=p^(n+1)？Is it real FLT?

# How
It should "any non-zero integer a
and a prime number p then a raised to the power p-1 always results in anumber 1 mod p "

**Comment by boland25** [comment]
@Hang-shao thanks for pointing this out.  Can you show us where you came across this in the repo?  thanks!

**Comment by boland25** [comment]
@Hang-shao ah I see it, its in the Readme of BGV_country_db_lookup, thanks!

**Comment by boland25** [comment]
@Hang-shao We are correcting the text to read like so....

For the next step, one should be aware of a mathematical result known as 
Fermat's little theorem (FLT). FLT implies that given any non-zero integer `a` 
and a prime number `p`, if `a` is not divisible by `p` then `a^(p-1)-1` is an 
integer multiple of `p`. Or to put it another way, `a^(p-1)` modulo `p` equals 1.
This is formally captured below. Using this result we can modify it slightly to
 produce a function `f(x)` as stated below.

**Comment by Hang-shao** [comment]
My goodness, thank you
I understand,![image](https://user-images.githubusercontent.com/50350694/121326391-178d6180-c945-11eb-8965-29c0db576b5d.png)，thanks again
