### ISSUE TITLE
Question about the built libraries libhelib.so and libmlhelib.a

### ISSUE THREAD

**Issue by DylanWangWQF** [IBM/fhe-toolkit-linux#169]
**Question**
In the built Alpine Docker container, I found the static library `libmlhelib.a` and dynamic library `libhelib.so`.

So we didn't build the static library `libhelib.a` in this example? (I need this library built on  Alpine Linux for my experiment)

**Comment by DylanWangWQF** [comment]
Sry about the wrong label `bug`.

**Comment by dubek** [comment]
Hi @DylanWangWQF, thank you for your interest in IBM's FHE toolkit.

Indeed by default we build only the shared library of HElib, as seen in `Dockerfile.ALPINE.HElib`:

```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED=ON -DENABLE_THREADS=ON ..
```

if you'll change that to `-DBUILD_SHARED=OFF` it should build the `libhelib.a` file. I expect the rest of the setup to keep working even with the static library (`.a`) but I haven't tried that.

**Comment by dubek** [comment]
> BTW, once I manually rebuild `HElib` to get `libhelib.a`, I found it does require the NTL and GMP to be the shared libraries `.so`. Here, I have a question. When I use `libhelib.a` in my own project, it's not available to work on `libntl.a` and `libgmp.a`?

I *think* this might be related to different licenses of GMP, NTL, and HElib and their ability to (legally) link together.

**Comment by boland25** [comment]
@DylanWangWQF @dubek  is correct in saying that if you build HElib as a static library it requires NTL and GMP to also be built as static.  It may be a situation that if you turn off SHARED in the HElib, it will expect that you are feeding it NTL and GMP libraries that are also .a and it isn't there so it doesn't build.  

You can look at the [macOS](https://github.com/ibm/fhe-toolkit-macos) repo to see how we build everything statically and run it there.  The flags would generally be the same for your alpine build.

Also NTL and GMP are different licenses than HElib so if you are planning on packaging and using this commercially it would require you to use shared libraries (.so)

**Comment by DylanWangWQF** [comment]
Hi, @boland25  @dubek .  I see.
Many thanks for your help!

**Comment by DylanWangWQF** [comment]
Sry, I reopen this issue. @dubek  @boland25 
I have a question about the use  of  `libhelib.a` on `libntl.a` and `libgmp.a`. Could you give me some suggestions? Thank you in advance!!!

Here is a simple sample code, the Github address: [Sample Code](https://github.com/DylanWangWQF/staticHelibTest)
```
HElibtest
-src
      *.cpp
      *.h
      BGV_test.cpp
      BGV_test.h
      Makefile
-TMat
     main.cpp
     Makefile
```
I extract these *.cpp files from HElib, make it simpler and package as `libhelib.a`.
Here is the simple written makefile:
```
src.Makefile:

clean:
    rm libhelib.a
all:
    g++ -c -I/usr/local/include -pthread -std=c++17 *.cpp
    ar rc libhelib.a *.o
    rm *.o

TMat.Makefile:

all:
    g++ -static main.cpp -o TestHE -L/usr/local/lib ../src/libhelib.a -lntl -lgmp -lm -std=c++17 -O2 -I/../src -pthread
clean:
    rm TestHE
```
After build and run, I got the below error:
```
test BGV_packed_arithmetric starts: 
Initialising context object...
Segmentation fault (core dumped)
```

But when I change the compile command to `g++ -std=c++17 -g -O2 -pthread main.cpp -o TestHE -L/usr/local/lib ../src/libhelib.a -lntl -lgmp -lm -I/../src` by removing `-static`, test run successfully.

It seems that `libhelib.a` cannot link against `libntl.a`.

**Comment by DylanWangWQF** [comment]
Sry for reopening this issue again.
@dubek  @boland25 
I want to install GMP by myself inside the alpine container. But it doesn't work after I modify the dockerfile.alpine (as well as alpine.HElib).

And I don't have permission to `./configure` inside the container to install the GMP and build other packages.

**Comment by dubek** [comment]
@DylanWangWQF You can always start you own Dockerfile from scratch to install whatever you need in it. Not sure this is related to fhe-toolkit-linux.

**Comment by DylanWangWQF** [comment]
@dubek  Thank you for your help! This has been solved.
