### ISSUE TITLE
Test script for BGV_country_lookup example

### ISSUE THREAD

**Issue by rosielickorish** [IBM/fhe-toolkit-linux#18]
**Feature description**
Automated test script to run BGV_country_lookup example needed to provide stability as development continues.

**Acceptance criteria**

1. Test script successfully run on test Jenkins service

**Comment by dowem** [comment]
This is pending a signature on the commit but otherwise looks ok to merge and is approved.

**Comment by dowem** [comment]
This issue seems to be closed with the most recent PR https://github.com/IBM/fhe-toolkit-linux/pull/27
