### ISSUE TITLE
Install pyhelayers offline.

### ISSUE THREAD

**Issue by Q410922** [IBM/fhe-toolkit-linux#191]
Hello! Your work are very excellent.
I successfully run the pyhelayers in the docker image. These tutorials are very nice.
But I replaced my computer because of memory limitations.
How to install pyhelayers offline? Because my new computer can't connect to the Internet.
I tried to use “pip install pyhelayers” for offline installation. (https://github.com/IBM/helayers)
But this pyhelayers version is different from the version in docker image.

**Comment by boland25** [comment]
Hi thanks for trying out our work!  Unfortunately you need an internet connection to be able to download the docker images.  However, it seems like you have some way of getting onto the internet.  I would suggest downloading the image on the machine connected to the internet using `docker save` and then transferring from one machine to the other.  Link to [docker save](https://docs.docker.com/engine/reference/commandline/save/).  Then on the other side, the machine you want to put it on, you run `docker import`.  Link to [docker import](https://docs.docker.com/engine/reference/commandline/import/).  Hopefully you are able to do that in some fashion.  that is the best setup I can think of for your problem.

**Comment by Q410922** [comment]
> 嗨，感谢您尝试我们的工作！不幸的是，您需要互联网连接才能下载 docker 映像。但是，您似乎有某种方式进入互联网。我建议在连接到互联网的机器上下载图像，然后从一台机器传输到另一台机器。链接到[码头工人保存](https://docs.docker.com/engine/reference/commandline/save/)。然后在另一边，你想穿上的机器，你跑。链接到[码头工人导入](https://docs.docker.com/engine/reference/commandline/import/)。希望您能够以某种方式做到这一点。这是我能想到的针对您的问题的最佳设置。`docker save``docker import`

Thanks for your reply!!!
I will have a try.
Thanks again.
