### ISSUE TITLE
Error : nnp.init_from_onnx

### ISSUE THREAD

**Issue by Q410922** [IBM/fhe-toolkit-linux#193]
Hello!
I saved my model. But when I use the following command, the program reports an error.

![111](https://user-images.githubusercontent.com/87742849/201094986-28c98dac-3a1f-4b95-b907-9cb75fd8ffb9.png)

**Comment by Q410922** [comment]
The framework of the model has no errors because it can be trained successfully.

**Comment by Q410922** [comment]
Looking forward to your prompt reply. Thank you！

**Comment by Q410922** [comment]
When I delete "bias=False", I solve this problem.
But I meet the new problem.

"RuntimeError: Bad data type 7 for tensor"

**Comment by boland25** [comment]
I think this has to be an area where @dubek or @aehud get involved.

**Comment by aehud** [comment]
Hi. Thanks for notifying us these issues.

Regarding the convolution, you are right, we currently don't support convolution without bias. We plan to add this support soon. Also we plan to improve error messages, and in fact the latest version, 1.5.0.3, already has some improved messages. You are welcome to check it.

Regarding the second issue: we currently support floating point datatype for the values provided in the onnx file, e.g., for weights of the various layers, and also as part of the activation layers definition. Here too we plan to extend this support and improve error messages.

In the meantime: 
* Try to see if you can convert your model to use only floats.
* We can help if you can provide more details: do you know in which layer you are using integers? From which library are you creating the onnx file?

Thanks.
