### ISSUE TITLE
CentOS

### ISSUE THREAD

**Issue by mzzd1111** [IBM/fhe-toolkit-linux#194]
Hello!
Can it be installed in CentOS systems？
"docker pull ibmcom/helayers-pylab:latest"

**Comment by Q410922** [comment]
I am currently renting a cloud server with CentOS installed, so I would like to know if "helayers-pylab" can be used in CentOS.

**Comment by mzzd1111** [comment]
I am currently renting a cloud server with CentOS installed, so I would like to know if "helayers-pylab" can be used in CentOS.

**Comment by dubek** [comment]
Hello @mzzd1111 ,

The easiest way is to install Docker on your server, and then run `docker pull icr.io/helayers/helayers-pylab:latest` (note that we're in the process of moving the Docker images to IBM Container Registry `icr.io`).

If you're interested in the Python library itself, you can install it with `pip install pyhelayers`.

**Comment by mzzd1111** [comment]
> 
Thanks for your reply!

I successfully installed pyhelayers using "pip install pyhelayers", but it seems to be different from the version in the docker image.
Because When I execute `optimizer = pyhelayerslite.HeProfileOptimizer(nnp, context)`，it made an error:
`module 'pyhelayers' has no attribute 'HeProfileOptimizer'`

**Comment by mzzd1111** [comment]
Thanks for your reply!

I successfully installed pyhelayers using "pip install pyhelayers", but it seems to be different from the version in the docker image.
Because When I execute `optimizer = pyhelayerslite.HeProfileOptimizer(nnp, context)`，
it made an error:
`module 'pyhelayers' has no attribute 'HeProfileOptimizer'`

**Comment by mzzd1111** [comment]
> Hello @mzzd1111 ,
> 
> The easiest way is to install Docker on your server, and then run `docker pull icr.io/helayers/helayers-pylab:latest` (note that we're in the process of moving the Docker images to IBM Container Registry `icr.io`).
> 
> If you're interested in the Python library itself, you can install it with `pip install pyhelayers`.

Thanks for your reply!

I successfully installed pyhelayers using "pip install pyhelayers", but it seems to be different from the version in the docker image.
Because When I execute `optimizer = pyhelayerslite.HeProfileOptimizer(nnp, context)`，
it made an error:
`module 'pyhelayers' has no attribute 'HeProfileOptimizer'`

**Comment by mzzd1111** [comment]
> I see `pyhelayerslite` there - why?

I'm sorry, I made a basic mistake.
I've solved the problem now. 
Thank you very much.
