### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by prusu01** [IBM/fhe-toolkit-linux#201]
**Feature description**
Is there anyway to paralelize computations using cuda on GPU at the moment?
If not, is there a plan to add it in the near future?

**Comment by boland25** [comment]
hey @prusu01 thanks for reaching out.  Your questions really are about a more deeper level than what we did on the toolkit.  The toolkit is more of a wrap around for the helib library so it can be easily used.  We don't support this much anymore but it's still available for download if someone wanted to work with it.  We have moved on to the next step of our SDK called HElayers. [https://ibm.github.io/helayers/](https://ibm.github.io/helayers/).  If you specifically are looking for HELib improvements, I would reach out the [helib GitHub maintainers](https://github.com/homenc/HElib) and see what they have plans for on their side.  Or you can check in with the
