### ISSUE TITLE
Addition of Alpine Linux as a container type

### ISSUE THREAD

**Issue by lizjmaple** [IBM/fhe-toolkit-linux#24]
Create base HELib container and toolkit containers for Alpine Linux, then plumb these into all setup and configuration scripting.

**Comment by lizjmaple** [comment]
Would like to assign this to myself, but am unable to.

**Comment by faberga** [comment]
@lizjmaple Done

**Comment by dowem** [comment]
As an update to this issue, we are working on it, and hopefully, it can land soon for anyone int the community who wants to try it.

**Comment by dowem** [comment]
Alpine is indeed now supported in the builds as well as in fetchable images from DockerHub 👍🏻  Rejoice Alpine lovers!
