### ISSUE TITLE
EACCES: permission denied, mkdir '/opt/IBM/FHE-Workspace/build' {}

### ISSUE THREAD

**Issue by guikarai** [IBM/fhe-toolkit-linux#25]
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Host Info (The machine hosting the FHE Toolkit Docker container), please provide the output of running the following commands in a termina window:
   - `uname -`
   - `ulimit -a`
 - Docker version (run `docker -v` in Terminal):
 - Toolkit platform (Fedora, CentOS, Ubuntu):

**Additional context**

**Comment by guikarai** [comment]
Issue is closed.
We had to grant more access on the host. Not it is working.

All credits and thanks to E.Phan.

**Comment by dowem** [comment]
I am glad you got it working @guikarai ! I hope the rest of the toolkit experience goes well. Please make sure to take our survey to help us improve!
