### ISSUE TITLE
C/C++ Extension failing to install

### ISSUE THREAD

**Issue by rosielickorish** [IBM/fhe-toolkit-linux#42]
**Describe the bug**
Shortly after starting a locally built instance of the toolkit on macOS, an error sometimes inteprets the compiler configuration, build or launch of the demos saying:

[Error - 7:02:21 PM] Connection to server got closed. Server will not be restarted.
/lib/ld-linux-aarch64.so.1: No such file or directory

At this point, it's still possible to build and run the demos. There is alway a warning saying that the C/C++ extention fails to install. Attempting to repair results in the above error and the toolkit then needing to be restarted. The behaviour isn't constant but and sometimes doesn't appear to be an issue, but other times the error continues to interrupt buildng and launching the demo.

**To Reproduce**
1. Run the toolkit locally built toolkit using `./RunToolkit.sh -l ubuntu`,
2. Open the toolkit and see the error appear in Output and in the bottom right corner of the toolkit (see screenshot).
3. If the appear doesn't appear straight away, refreshing the toolkit seems to make it appear.

**Expected behavior**
The toolkit should start without errors and it should be possible to build and launch the demos.

**Screenshots**
![Screenshot 2020-09-29 at 19 57 39](https://user-images.githubusercontent.com/14885679/94604087-13298880-028f-11eb-9c4d-571a08020d13.png)
![Screenshot 2020-09-29 at 20 00 51](https://user-images.githubusercontent.com/14885679/94604096-16bd0f80-028f-11eb-85f7-4e6cbb25c318.png)

**Environment (please complete the following information):**
 - Host Info (The machine hosting the FHE Toolkit Docker container), please provide the output of running the following commands in a termina window:
   - `uname -`Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
   - `ulimit -a`
```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2784
-n: file descriptors                12800
```
 - Docker version (run `docker -v` in Terminal): Docker version 19.03.12, build 48a66213fe
 - Toolkit platform (Fedora, CentOS, Ubuntu): Ubuntu (not tested on other platforms)

**Additional context**
ms-vscode.cpptools v1.0.1
https://github.com/cdr/code-server/issues/2120

**Comment by rosielickorish** [comment]
Rolling back `ms-vscode.cpptools` to 0.29.0 seems to fix this issue.

**Comment by welljsjs** [comment]
Out of curiosity because we're having the same issue, are you really rolling back to v0.29.0 from v1.0.1?

**Comment by rosielickorish** [comment]
The issue is still there at v1.0.0 so it looks like the best solution for now is to roll back to cpptools v0.29.0.

**Comment by dowem** [comment]
With the pinned older version this seems to work for now ... sorry @welljsjs we will have to revisit this for a newer version at some point! Keep us honest about this if it is an issue you care about after our next stable release :)
