### ISSUE TITLE
Credit card fraud example should support out-the-box build and launchfrom the IDE GUI

### ISSUE THREAD

**Issue by rosielickorish** [IBM/fhe-toolkit-linux#6]
**Feature description**
The credit card fraud example doesn't currently support the same out-of-the-box build and launch as the other demos.

**Acceptance criteria**

1. It should be possible to build and run each of the five examples in the same way using the build and launch button in the Toolkit.

**Comment by dowem** [comment]
Right now a workaround is to navigate using the shell or console to the examples directory, then into the credit card fraud directory. From the top level type "cmake ." to initiate a cmake. Then type "make" to compile and link the example. From the build directory you can run  the credit card example executable (it takes no arguments).

**Comment by dowem** [comment]
@rosielickorish are you still interested in this? Or shall I reassign it to another developer if you don't have time to dig into this :)

**Comment by rosielickorish** [comment]
@dowem sadly no time available to solve this one so best to reassign :)

**Comment by dowem** [comment]
Dean has a patch and Greg will be testing it today or tomorrow. As soon as it is validated as complete we will merge it.
