### ISSUE TITLE
Can you publish roadmap for Production Release for IOS ?

### ISSUE THREAD

**Issue by rekhakm** [IBM/fhe-toolkit-linux#68]
Currently this support only IOS simulator.. Can you please confirm when can we expect the final General release for IOS devices ?
 
Road map for Android will also help

**Comment by dowem** [comment]
Hello @rekhakm this is the Linux toolkit GitHub and your questions are about iOS and Android. I will refer you to this issue in our iOS GitHub repository; https://github.com/IBM/fhe-toolkit-ios/issues/13. Feel free to add a comment there or a thumbs up to show support for iOS native execution without relying on the simulator. 

As for android support, that is on hold indefinitely while we work on other projects. If there is interest in Android support feel free to open a tracker issue here: https://github.com/IBM/fhe-toolkit-android/issues and hopefully others will give it a thumbs up to indicate strong support. Right now our team is not large enough to support all these platforms without a serious showing of interest in the community.
