### ISSUE TITLE
Add bats-core to base HElib container

### ISSUE THREAD

**Issue by faberga** [IBM/fhe-toolkit-linux#69]
**Requirement description**
`bats-core v1.2.1` is required for the HElib >= v1.1.x utils tests/examples.
https://github.com/bats-core/bats-core/releases/tag/v1.2.1

**Acceptance criteria**

1. bats-core is installed 
2. pass HElib utils tests/examples.

**Comment by dowem** [comment]
@faberga are you planning to send a commit for this one? If so is there any timeline for that

**Comment by dowem** [comment]
@boland25 can you confirm today that bats-core is needed in the toolkit runtime for the HElib tests? If so let us add it in the toolkit base images and close this issue out while you are updating the containers as you check the Doxygen stuff today.

**Comment by boland25** [comment]
@dowem sure!

**Comment by dowem** [comment]
Any update on this one? We should tackle this one BEFORE the 2.0.0 HElib update so the tests all run nicely :)

**Comment by boland25** [comment]
will be closed out after PR #104 is merged into master

**Comment by dowem** [comment]
Merged 104, so we can close this one out. Thanks, @boland25  for making it happen!
