### ISSUE TITLE
CMakeList.txt of the BGV_database_lookup points to the old HElib version

### ISSUE THREAD

**Issue by christianepeters** [IBM/fhe-toolkit-linux#71]
The CMakeList.txt of the BGV_database_lookup points to the old HElib version.

It should be `find_package(helib ${HELIB_VERSION} REQUIRED)`
```
# Use -std=c++14 as default.
set(CMAKE_CXX_STANDARD 14)
# Disable C++ extensions
set(CMAKE_CXX_EXTENSIONS OFF)
# Require full C++ standard
set(CMAKE_CXX_STANDARD_REQUIRED ON)
project(BGV_database_lookup LANGUAGES CXX)
#find_package(helib 1.0.0 REQUIRED)
find_package(helib ${HELIB_VERSION} REQUIRED)
add_executable(BGV_database_lookup BGV_database_lookup.cpp)
target_link_libraries(BGV_database_lookup helib)
```

**Comment by boland25** [comment]
nice find thank you!

**Comment by boland25** [comment]
I checked the file that you pointed out has the old version, and in master it is updated.  https://github.com/IBM/fhe-toolkit-linux/blob/master/samples/BGV_country_db_lookup/CMakeLists.txt. Perhaps you need to update your local copy?  Not sure why you are seeing this

**Comment by boland25** [comment]
going to close this out for now, if you respond with something I missed, we can definitely re-open. Thanks for opening!
