### ISSUE TITLE
DOC SPRINT - CKKS examples

### ISSUE THREAD

**Issue by vidstrancar** [IBM/fhe-toolkit-linux#74]
Hi, could you maybe provide some examples how to use ckks scheme inside helib?
Also is bgv/ckks bootstrapping supported?
Also to choose safe encryption parameters should i just refer to the publicly published tables or is there some helper function?
And is there any actual documentation?

**Comment by dowem** [comment]
hi @vidstrancar  I have been on holiday, sorry for the delay in response. Can you tell me what kind of examples you want to see specifically? Please spell it out as clearly as possible and if it is something we can do we will provide an example. If more than one example is wanted (that are nontrivially different) open separate issues for them please :)

As to the safe encryption parameters, I will tag @faberga here to point you to the docs. We do have API documents generated by doxygen but they might not be what you need. There are some helper code in helib that Flavio can point you to.  

I am planning a documentation sprint for our team in the near future which I hope can address these better in the long term, in the short term lets try to get you pointed at what we already have

**Comment by dowem** [comment]
Greg, once we merge helib 2.0.0 (sometime in the immediate future), can we get these answers for @vidstrancar and post them here. There should be obvious places where to point for the new docs you have been working on.

**Comment by dowem** [comment]
@vidstrancar  The newest version of our toolkit includes the new CKKS tutorials (from HElib). If you use the toolkit the examples are included but you can also review the source of these here: https://github.com/IBM-HElib/HElib/tree/master/examples/tutorial   Thank you for your patience! Please reopen the issue if this was not helpful, or open other issues if you see things you would like to see improved.
