### ISSUE TITLE
DOC SPRINT - Make sure Checked in Docs match HElib and toolkiit version

### ISSUE THREAD

**Issue by dowem** [IBM/fhe-toolkit-linux#76]
**Describe the bug**
At present the version of the docs checked in on a tagged or released branch may not match the code. We need to adjust our build pipeline/process to make sure this is done automatically to keep docs in sync.

**Comment by dowem** [comment]
I think we can close this after merges: https://github.com/IBM/fhe-toolkit-linux/pull/104 and https://github.com/IBM/fhe-toolkit-linux/pull/97

@boland25  can you confirm? If so we can close this one! 🥳

**Comment by boland25** [comment]
this is something I wanted to discuss as the script is not checking versions, its just generating docs, we might to put a check in place to statisfy this one

**Comment by dowem** [comment]
@boland25 I am going to close this one given your merged fix from yesterday! Thanks for the patch Please reopen this if I have closed it prematurely.
