### ISSUE TITLE
Curl (77) error on zCX in BuildDockerImage.sh

### ISSUE THREAD

**Issue by rosielickorish** [IBM/fhe-toolkit-linux#9]
**Describe the bug**
On zCX the default curl invocations fails complaining about certificate locations. I had to add -k (or the more obvious --insecure) flag to ignore checking keys. It would seem the system I am running is not capable of comparing to a key store.

**To Reproduce**
1. Run `./BuildDocker <platform>` on zCX
2. See error:
```
Checking for cached NTL download...
INFO: Attempting to download NTL with the curl command...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (77) error setting certificate verify locations:
CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
FATAL: There was an issue downloading NTL-11.4.3 from 
```

**Expected behavior**
The `BuildDockerImage.sh` script should run on zCX without needing to alter the curl command 

**Environment (please complete the following information):**
 - Host Info (The machine hosting the FHE Toolkit Docker container), please provide the output of running the following commands in a termina window:
   - `uname -` `Linux CB8ACX1 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:31:47 UTC 2020 s390x s390x s390x GNU/Linux`
   - `ulimit -a`
```
 ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 46934
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
 - Docker version (run `docker -v` in Terminal): Docker version 19.03.6, build 369ce74a3c
 - Toolkit platform (Fedora, CentOS, Ubuntu): Fedora and Ubuntu

**Comment by dowem** [comment]
As a known workaround, add the -k option to each of the curl invocations. This works but it reduces curl security. The issue in zCX curl implementation has been raised within IBM, but there is no official ETA on a fix. I think in the meantime we should add an ifdef style support to add the -k flag when running in a zCX context for a good out of the box experience.

**Comment by dowem** [comment]
@boland25  has a patch awaiting final test verification. As soon as it is done, we expect a PR :) Thank you to anyone waiting on this issue for their continued patience.

**Comment by dowem** [comment]
Fixed in PR: https://github.com/IBM/fhe-toolkit-linux/pull/32
